name: garage_management
description: "A mobile app to manage your Car Garage"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter # Required for localization support
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  font_awesome_flutter: ^10.6.0  # Updated to the latest stable version
  iconly: ^1.0.1
  http: ^1.3.0
  intl: ^0.19.0  # Recommended for localization & date formatting
  path_provider: ^2.1.2  # Required for storing config JSON file

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Adjusted version for compatibility

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
